/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEntropyConsumerInterface extends ethers.utils.Interface {
  functions: {
    "_entropyCallback(uint64,address,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_entropyCallback",
    values: [BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_entropyCallback",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEntropyConsumer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEntropyConsumerInterface;

  functions: {
    _entropyCallback(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "_entropyCallback(uint64,address,bytes32)"(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  _entropyCallback(
    sequence: BigNumberish,
    provider: string,
    randomNumber: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "_entropyCallback(uint64,address,bytes32)"(
    sequence: BigNumberish,
    provider: string,
    randomNumber: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    _entropyCallback(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "_entropyCallback(uint64,address,bytes32)"(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    _entropyCallback(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "_entropyCallback(uint64,address,bytes32)"(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _entropyCallback(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "_entropyCallback(uint64,address,bytes32)"(
      sequence: BigNumberish,
      provider: string,
      randomNumber: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
