/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { CoinFlipErrors } from "../CoinFlipErrors";

export class CoinFlipErrors__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<CoinFlipErrors> {
    return super.deploy(overrides || {}) as Promise<CoinFlipErrors>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CoinFlipErrors {
    return super.attach(address) as CoinFlipErrors;
  }
  connect(signer: Signer): CoinFlipErrors__factory {
    return super.connect(signer) as CoinFlipErrors__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoinFlipErrors {
    return new Contract(address, _abi, signerOrProvider) as CoinFlipErrors;
  }
}

const _abi = [
  {
    inputs: [],
    name: "IncorrectSender",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientFee",
    type: "error",
  },
];

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220d3e23ba8e6760287dd2a5b45bb7b8ff5cef36ba6a0f25a31a3ad94e3a5b34aa264736f6c63430008130033";
