/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IEntropyConsumer } from "../IEntropyConsumer";

export class IEntropyConsumer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEntropyConsumer {
    return new Contract(address, _abi, signerOrProvider) as IEntropyConsumer;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "sequence",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "randomNumber",
        type: "bytes32",
      },
    ],
    name: "_entropyCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
