/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { VRFV2PlusClient } from "../VRFV2PlusClient";

export class VRFV2PlusClient__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<VRFV2PlusClient> {
    return super.deploy(overrides || {}) as Promise<VRFV2PlusClient>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): VRFV2PlusClient {
    return super.attach(address) as VRFV2PlusClient;
  }
  connect(signer: Signer): VRFV2PlusClient__factory {
    return super.connect(signer) as VRFV2PlusClient__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VRFV2PlusClient {
    return new Contract(address, _abi, signerOrProvider) as VRFV2PlusClient;
  }
}

const _abi = [
  {
    inputs: [],
    name: "EXTRA_ARGS_V1_TAG",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60808060405234601857607b908161001e823930815050f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c63f7514ab414602657600080fd5b600036600319011260405763125fa26760e31b8152602090f35b600080fdfea26469706673582212203dedaa3d1478b374b281d318567a8c0e3be35ce4e45d95c46b0d730e715f3a7964736f6c63430008130033";
